### ISSUE TITLE
Fix Bug that causes the match to DRAW even when a player has already won

### ISSUE THREAD

**Issue by till-tomorrow** [till-tomorrow/Tic-Tac-Toe#9]
Fix the issue which is causing the TIC-TOC-TOE match to DRAW even when Player 1 has won the game(by placing a **X** at the position1 in the grid).

**Comment by ENiGMA9** [comment]
Hello, I would like to take on this issue!

**Comment by ENiGMA9** [comment]
Can you please provide details for correctly building the game? Thanks.

**Comment by rohan20** [comment]
Fixed and created PR.
PS: Please always upload the whole Android Studio project and not just some files.

**Comment by till-tomorrow** [comment]
Thanks a ton...and I will, from next time onwards! @rohan20

**Comment by till-tomorrow** [comment]
@ENiGMA9 
Currently, the game has a bug which causes the game to DRAW even when a player has already won. It happens when only the last box in the grid is left to be filled. The game generally ends up at the DRAW even if that very last move of a player is the winning move! I am not able to fix the issue yet. If you can, go ahead. All the best!
